import bcrypt from "bcrypt";
// import { v4 as uuidv4 } from "uuid";
import logger from "../uitls/logger.ts";
import Job from "../models/job.model.ts";
import User from "../models/user.model.ts";
import connectDb from "../config/db.ts";
import "dotenv/config";

const jobs = [
	// Google Jobs (15 positions)
	{
		title: "Software Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/google.com",
		isBookmarked: false,
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Join Google's innovative engineering team to build scalable web applications and cloud services. Work on cutting-edge projects using TypeScript, Node.js, React, and Kubernetes. Collaborate with world-class engineers in a fast-paced environment. Responsibilities include designing RESTful APIs, optimizing database performance, implementing CI/CD pipelines, and mentoring junior developers. Perfect for intermediate engineers passionate about distributed systems and modern web technologies.",
		company: "Google",
		location: "San Francisco, CA",
		salary: "100,000 - 120,000",
		createdAt: new Date("2022-03-15T23:31:24.396Z"),
		updatedAt: new Date("2022-03-15T23:31:24.396Z"),
	},
	{
		title: "Senior Node.js Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/google.com",
		company: "Google",
		location: "Mountain View, CA",
		salary: "140,000 - 170,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Lead Google's cloud API development with Node.js, TypeScript, and gRPC. Design scalable microservices for GCP and optimize for 10M+ req/sec.",
		isBookmarked: false,
		createdAt: new Date("2022-03-15T23:31:24.396Z"),
		updatedAt: new Date("2022-03-15T23:31:24.396Z"),
	},
	{
		title: "DevOps Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/google.com",
		company: "Google",
		location: "Remote",
		salary: "130,000 - 160,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Build Kubernetes CI/CD pipelines for Google's internal tools using Terraform, Jenkins, and Node.js automation scripts.",
		isBookmarked: false,
		createdAt: new Date("2022-03-15T23:31:24.396Z"),
		updatedAt: new Date("2022-03-15T23:31:24.396Z"),
	},
	{
		title: "Front End Developer",
		type: "Full Time",
		logo: "https://logos.hunter.io/google.com",
		company: "Google",
		location: "New York, NY",
		salary: "110,000 - 135,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Build Google Workspace interfaces with React, TypeScript, and Material-UI. Focus on accessibility and internationalization.",
		isBookmarked: false,
		createdAt: new Date("2022-04-10T10:15:00.000Z"),
		updatedAt: new Date("2022-04-10T10:15:00.000Z"),
	},
	{
		title: "Full Stack Developer",
		type: "Hybrid",
		logo: "https://logos.hunter.io/google.com",
		company: "Google",
		location: "Austin, TX",
		salary: "115,000 - 140,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Develop Google Maps features using Node.js, Angular, and Python. Work on location-based services and real-time data processing.",
		isBookmarked: false,
		createdAt: new Date("2022-05-22T14:30:00.000Z"),
		updatedAt: new Date("2022-05-22T14:30:00.000Z"),
	},
	{
		title: "Back End Developer",
		type: "Full Time",
		logo: "https://logos.hunter.io/google.com",
		company: "Google",
		location: "Seattle, WA",
		salary: "120,000 - 150,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Design and implement Google Search backend services using C++, Java, and distributed systems.",
		isBookmarked: false,
		createdAt: new Date("2022-06-05T09:45:00.000Z"),
		updatedAt: new Date("2022-06-05T09:45:00.000Z"),
	},
	{
		title: "Site Reliability Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/google.com",
		company: "Google",
		location: "Remote",
		salary: "135,000 - 165,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Ensure 99.99% availability for Google Cloud services. Implement monitoring, chaos engineering, and incident response.",
		isBookmarked: false,
		createdAt: new Date("2022-07-12T11:20:00.000Z"),
		updatedAt: new Date("2022-07-12T11:20:00.000Z"),
	},
	{
		title: "Software Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/google.com",
		company: "Google",
		location: "Chicago, IL",
		salary: "105,000 - 125,000",
		currency: "USD",
		experienceLevel: "Entry Level",
		description:
			"Join Google's engineering residency program. Rotate through different teams and technologies including web, mobile, and cloud.",
		isBookmarked: false,
		createdAt: new Date("2022-08-18T13:10:00.000Z"),
		updatedAt: new Date("2022-08-18T13:10:00.000Z"),
	},
	{
		title: "Product Manager",
		type: "Full Time",
		logo: "https://logos.hunter.io/google.com",
		company: "Google",
		location: "Mountain View, CA",
		salary: "150,000 - 180,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Lead product strategy for Google Ads. Work with engineering, design, and marketing teams to drive ad revenue growth.",
		isBookmarked: false,
		createdAt: new Date("2022-09-03T15:40:00.000Z"),
		updatedAt: new Date("2022-09-03T15:40:00.000Z"),
	},
	{
		title: "Data Scientist",
		type: "Full Time",
		logo: "https://logos.hunter.io/google.com",
		company: "Google",
		location: "San Francisco, CA",
		salary: "140,000 - 170,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Analyze user behavior data to improve Google Search algorithms. Use Python, TensorFlow, and BigQuery.",
		isBookmarked: false,
		createdAt: new Date("2022-09-28T08:30:00.000Z"),
		updatedAt: new Date("2022-09-28T08:30:00.000Z"),
	},
	{
		title: "UI/UX Designer",
		type: "Full Time",
		logo: "https://logos.hunter.io/google.com",
		company: "Google",
		location: "New York, NY",
		salary: "115,000 - 140,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Design intuitive interfaces for Google Assistant. Create wireframes, prototypes, and user flows.",
		isBookmarked: false,
		createdAt: new Date("2022-10-14T12:15:00.000Z"),
		updatedAt: new Date("2022-10-14T12:15:00.000Z"),
	},
	{
		title: "Mobile Developer",
		type: "Full Time",
		logo: "https://logos.hunter.io/google.com",
		company: "Google",
		location: "Remote",
		salary: "120,000 - 145,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Develop Android apps using Kotlin and Jetpack Compose. Focus on Material Design and performance optimization.",
		isBookmarked: false,
		createdAt: new Date("2022-11-07T10:00:00.000Z"),
		updatedAt: new Date("2022-11-07T10:00:00.000Z"),
	},
	{
		title: "Technical Writer",
		type: "Full Time",
		logo: "https://logos.hunter.io/google.com",
		company: "Google",
		location: "Sunnyvale, CA",
		salary: "90,000 - 110,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Create documentation for Google Cloud APIs. Write developer guides, API references, and tutorials.",
		isBookmarked: false,
		createdAt: new Date("2022-11-22T14:50:00.000Z"),
		updatedAt: new Date("2022-11-22T14:50:00.000Z"),
	},
	{
		title: "Security Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/google.com",
		company: "Google",
		location: "Austin, TX",
		salary: "130,000 - 160,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Conduct security audits and penetration testing for Google products. Implement security best practices.",
		isBookmarked: false,
		createdAt: new Date("2022-12-09T09:20:00.000Z"),
		updatedAt: new Date("2022-12-09T09:20:00.000Z"),
	},
	{
		title: "QA Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/google.com",
		company: "Google",
		location: "Remote",
		salary: "95,000 - 115,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Develop automated test frameworks for Chrome browser. Use Selenium, Puppeteer, and JavaScript.",
		isBookmarked: false,
		createdAt: new Date("2023-01-05T11:30:00.000Z"),
		updatedAt: new Date("2023-01-05T11:30:00.000Z"),
	},

	// Meta Jobs (15 positions)
	{
		title: "Full Stack Developer",
		type: "Remote",
		logo: "https://logos.hunter.io/meta.com",
		isBookmarked: false,
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Build Meta's next-generation React applications and Node.js APIs. Work remotely with TypeScript, Next.js, GraphQL, and Prisma. Own full-stack features from database design to UI polish. Collaborate with product teams on scalable, performant web apps.",
		company: "Meta",
		location: "San Francisco, CA",
		salary: "100,000 - 120,000",
		createdAt: new Date("2022-03-15T23:31:24.396Z"),
		updatedAt: new Date("2022-03-15T23:31:24.396Z"),
	},
	{
		title: "Full Stack Developer",
		type: "Remote",
		logo: "https://logos.hunter.io/meta.com",
		isBookmarked: false,
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Develop Meta's social platform features using Express, PostgreSQL, and React. Focus on real-time features, authentication flows, and API optimization. Remote role with TypeScript mandate and modern dev practices.",
		company: "Meta",
		location: "San Francisco, CA",
		salary: "100,000 - 120,000",
		createdAt: new Date("2022-03-15T23:31:24.396Z"),
		updatedAt: new Date("2022-03-15T23:31:24.396Z"),
	},
	{
		title: "React Native Developer",
		type: "Remote",
		logo: "https://logos.hunter.io/meta.com",
		company: "Meta",
		location: "Menlo Park, CA",
		salary: "120,000 - 150,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Build Meta's mobile apps with React Native, TypeScript, and GraphQL. Focus on Quest VR integration and cross-platform performance.",
		isBookmarked: false,
		createdAt: new Date("2022-03-15T23:31:24.396Z"),
		updatedAt: new Date("2022-03-15T23:31:24.396Z"),
	},
	{
		title: "Front End Developer",
		type: "Hybrid",
		logo: "https://logos.hunter.io/meta.com",
		company: "Meta",
		location: "New York, NY",
		salary: "115,000 - 140,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Build Instagram web features using React, TypeScript, and custom UI libraries. Focus on performance and user engagement.",
		isBookmarked: false,
		createdAt: new Date("2022-04-15T08:45:00.000Z"),
		updatedAt: new Date("2022-04-15T08:45:00.000Z"),
	},
	{
		title: "Back End Developer",
		type: "Full Time",
		logo: "https://logos.hunter.io/meta.com",
		company: "Meta",
		location: "Seattle, WA",
		salary: "125,000 - 150,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Design scalable APIs for Facebook's news feed algorithm. Use Hack, PHP, and GraphQL.",
		isBookmarked: false,
		createdAt: new Date("2022-05-20T13:20:00.000Z"),
		updatedAt: new Date("2022-05-20T13:20:00.000Z"),
	},
	{
		title: "Data Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/meta.com",
		company: "Meta",
		location: "Remote",
		salary: "130,000 - 160,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Build data pipelines for Meta's ad targeting systems. Use Python, Spark, and Hive.",
		isBookmarked: false,
		createdAt: new Date("2022-06-28T10:10:00.000Z"),
		updatedAt: new Date("2022-06-28T10:10:00.000Z"),
	},
	{
		title: "Product Designer",
		type: "Full Time",
		logo: "https://logos.hunter.io/meta.com",
		company: "Meta",
		location: "San Francisco, CA",
		salary: "120,000 - 145,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Design new features for WhatsApp. Create intuitive messaging experiences and video calling interfaces.",
		isBookmarked: false,
		createdAt: new Date("2022-07-19T15:30:00.000Z"),
		updatedAt: new Date("2022-07-19T15:30:00.000Z"),
	},
	{
		title: "DevOps Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/meta.com",
		company: "Meta",
		location: "Remote",
		salary: "135,000 - 165,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Manage Kubernetes clusters for Meta's infrastructure. Implement CI/CD pipelines and monitoring solutions.",
		isBookmarked: false,
		createdAt: new Date("2022-08-11T09:00:00.000Z"),
		updatedAt: new Date("2022-08-11T09:00:00.000Z"),
	},
	{
		title: "Software Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/meta.com",
		company: "Meta",
		location: "Austin, TX",
		salary: "110,000 - 130,000",
		currency: "USD",
		experienceLevel: "Entry Level",
		description:
			"Join Meta's engineering bootcamp. Rotate through teams working on Facebook, Instagram, and WhatsApp.",
		isBookmarked: false,
		createdAt: new Date("2022-09-05T14:15:00.000Z"),
		updatedAt: new Date("2022-09-05T14:15:00.000Z"),
	},
	{
		title: "Machine Learning Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/meta.com",
		company: "Meta",
		location: "Menlo Park, CA",
		salary: "150,000 - 180,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Develop ML models for content recommendation. Use PyTorch, TensorFlow, and large-scale data.",
		isBookmarked: false,
		createdAt: new Date("2022-10-02T11:45:00.000Z"),
		updatedAt: new Date("2022-10-02T11:45:00.000Z"),
	},
	{
		title: "Site Reliability Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/meta.com",
		company: "Meta",
		location: "Remote",
		salary: "140,000 - 170,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Ensure reliability of Meta's real-time communication services. Focus on latency and availability.",
		isBookmarked: false,
		createdAt: new Date("2022-10-25T08:30:00.000Z"),
		updatedAt: new Date("2022-10-25T08:30:00.000Z"),
	},
	{
		title: "Security Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/meta.com",
		company: "Meta",
		location: "Seattle, WA",
		salary: "135,000 - 165,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Protect user data and prevent security breaches. Conduct threat modeling and security reviews.",
		isBookmarked: false,
		createdAt: new Date("2022-11-18T12:20:00.000Z"),
		updatedAt: new Date("2022-11-18T12:20:00.000Z"),
	},
	{
		title: "QA Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/meta.com",
		company: "Meta",
		location: "Remote",
		salary: "100,000 - 120,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Build automated testing frameworks for mobile apps. Use Detox, Jest, and Appium.",
		isBookmarked: false,
		createdAt: new Date("2022-12-08T15:50:00.000Z"),
		updatedAt: new Date("2022-12-08T15:50:00.000Z"),
	},
	{
		title: "Technical Program Manager",
		type: "Full Time",
		logo: "https://logos.hunter.io/meta.com",
		company: "Meta",
		location: "San Francisco, CA",
		salary: "145,000 - 175,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Lead cross-functional teams for Facebook Marketplace initiatives. Coordinate engineering, design, and product.",
		isBookmarked: false,
		createdAt: new Date("2023-01-12T10:05:00.000Z"),
		updatedAt: new Date("2023-01-12T10:05:00.000Z"),
	},
	{
		title: "Full Stack Developer",
		type: "Hybrid",
		logo: "https://logos.hunter.io/meta.com",
		company: "Meta",
		location: "Los Angeles, CA",
		salary: "115,000 - 140,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Build creator tools for Instagram Reels. Use React, Node.js, and video processing technologies.",
		isBookmarked: false,
		createdAt: new Date("2023-01-30T13:40:00.000Z"),
		updatedAt: new Date("2023-01-30T13:40:00.000Z"),
	},

	// Amazon Jobs (15 positions)
	{
		title: "Back End Developer",
		type: "Full Time",
		logo: "https://logos.hunter.io/amazon.com",
		isBookmarked: false,
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Scale Amazon's AWS services with Node.js, TypeScript, and DynamoDB. Build REST/GraphQL APIs, implement microservices, and optimize for millions of requests. Focus on security, monitoring, and CI/CD pipelines.",
		company: "Amazon",
		location: "San Francisco, CA",
		salary: "100,000 - 120,000",
		createdAt: new Date("2022-03-15T23:31:24.396Z"),
		updatedAt: new Date("2022-03-15T23:31:24.396Z"),
	},
	{
		title: "Serverless Architect",
		type: "Full Time",
		logo: "https://logos.hunter.io/amazon.com",
		company: "Amazon",
		location: "Seattle, WA",
		salary: "135,000 - 165,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Design AWS Lambda architectures with Node.js, API Gateway, and DynamoDB. Optimize cold starts and scale to enterprise workloads.",
		isBookmarked: false,
		createdAt: new Date("2022-03-15T23:31:24.396Z"),
		updatedAt: new Date("2022-03-15T23:31:24.396Z"),
	},
	{
		title: "Software Development Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/amazon.com",
		company: "Amazon",
		location: "Arlington, VA",
		salary: "115,000 - 140,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Build Amazon Prime Video features using Java, React, and AWS services. Focus on streaming quality and user experience.",
		isBookmarked: false,
		createdAt: new Date("2022-04-05T09:25:00.000Z"),
		updatedAt: new Date("2022-04-05T09:25:00.000Z"),
	},
	{
		title: "Front End Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/amazon.com",
		company: "Amazon",
		location: "Remote",
		salary: "110,000 - 135,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Develop Amazon.com product pages with React, TypeScript, and server-side rendering.",
		isBookmarked: false,
		createdAt: new Date("2022-05-17T14:50:00.000Z"),
		updatedAt: new Date("2022-05-17T14:50:00.000Z"),
	},
	{
		title: "DevOps Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/amazon.com",
		company: "Amazon",
		location: "Austin, TX",
		salary: "125,000 - 150,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Manage AWS infrastructure for internal tools. Use CloudFormation, Jenkins, and Python.",
		isBookmarked: false,
		createdAt: new Date("2022-06-22T11:15:00.000Z"),
		updatedAt: new Date("2022-06-22T11:15:00.000Z"),
	},
	{
		title: "Data Scientist",
		type: "Full Time",
		logo: "https://logos.hunter.io/amazon.com",
		company: "Amazon",
		location: "San Francisco, CA",
		salary: "140,000 - 170,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Optimize Amazon's supply chain with predictive analytics. Use Python, Spark, and ML algorithms.",
		isBookmarked: false,
		createdAt: new Date("2022-07-08T10:40:00.000Z"),
		updatedAt: new Date("2022-07-08T10:40:00.000Z"),
	},
	{
		title: "Security Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/amazon.com",
		company: "Amazon",
		location: "Seattle, WA",
		salary: "130,000 - 160,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Secure AWS infrastructure and customer data. Implement encryption and access controls.",
		isBookmarked: false,
		createdAt: new Date("2022-08-14T13:00:00.000Z"),
		updatedAt: new Date("2022-08-14T13:00:00.000Z"),
	},
	{
		title: "Full Stack Developer",
		type: "Hybrid",
		logo: "https://logos.hunter.io/amazon.com",
		company: "Amazon",
		location: "Chicago, IL",
		salary: "115,000 - 140,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Build Amazon Business tools for enterprise customers. Use React, Node.js, and PostgreSQL.",
		isBookmarked: false,
		createdAt: new Date("2022-09-19T08:55:00.000Z"),
		updatedAt: new Date("2022-09-19T08:55:00.000Z"),
	},
	{
		title: "Mobile Developer",
		type: "Full Time",
		logo: "https://logos.hunter.io/amazon.com",
		company: "Amazon",
		location: "Remote",
		salary: "120,000 - 145,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Develop Amazon Shopping app features for iOS using Swift and SwiftUI.",
		isBookmarked: false,
		createdAt: new Date("2022-10-03T12:30:00.000Z"),
		updatedAt: new Date("2022-10-03T12:30:00.000Z"),
	},
	{
		title: "Product Manager",
		type: "Full Time",
		logo: "https://logos.hunter.io/amazon.com",
		company: "Amazon",
		location: "Seattle, WA",
		salary: "150,000 - 180,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Lead Alexa voice shopping features. Define roadmap and work with engineering teams.",
		isBookmarked: false,
		createdAt: new Date("2022-10-27T15:20:00.000Z"),
		updatedAt: new Date("2022-10-27T15:20:00.000Z"),
	},
	{
		title: "Systems Development Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/amazon.com",
		company: "Amazon",
		location: "Austin, TX",
		salary: "125,000 - 155,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Build and maintain Amazon's internal infrastructure tools. Focus on automation and reliability.",
		isBookmarked: false,
		createdAt: new Date("2022-11-15T09:10:00.000Z"),
		updatedAt: new Date("2022-11-15T09:10:00.000Z"),
	},
	{
		title: "UX Researcher",
		type: "Full Time",
		logo: "https://logos.hunter.io/amazon.com",
		company: "Amazon",
		location: "Remote",
		salary: "110,000 - 135,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Conduct user research for Amazon Fresh. Improve grocery shopping experience through usability studies.",
		isBookmarked: false,
		createdAt: new Date("2022-12-02T11:45:00.000Z"),
		updatedAt: new Date("2022-12-02T11:45:00.000Z"),
	},
	{
		title: "QA Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/amazon.com",
		company: "Amazon",
		location: "San Francisco, CA",
		salary: "100,000 - 120,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Test Amazon Web Services console. Automate testing with Selenium and Python.",
		isBookmarked: false,
		createdAt: new Date("2023-01-09T14:35:00.000Z"),
		updatedAt: new Date("2023-01-09T14:35:00.000Z"),
	},
	{
		title: "Technical Writer",
		type: "Full Time",
		logo: "https://logos.hunter.io/amazon.com",
		company: "Amazon",
		location: "Seattle, WA",
		salary: "90,000 - 110,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Write documentation for AWS services. Create developer guides and API references.",
		isBookmarked: false,
		createdAt: new Date("2023-01-28T08:20:00.000Z"),
		updatedAt: new Date("2023-01-28T08:20:00.000Z"),
	},
	{
		title: "Software Development Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/amazon.com",
		company: "Amazon",
		location: "Remote",
		salary: "105,000 - 125,000",
		currency: "USD",
		experienceLevel: "Entry Level",
		description:
			"Join Amazon's SDE program. Work on customer-facing features with mentorship from senior engineers.",
		isBookmarked: false,
		createdAt: new Date("2023-02-15T10:50:00.000Z"),
		updatedAt: new Date("2023-02-15T10:50:00.000Z"),
	},

	// Tesla Jobs (15 positions)
	{
		title: "Front End Developer",
		type: "Onsite",
		logo: "https://logos.hunter.io/tesla.com",
		isBookmarked: false,
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Craft Tesla's vehicle dashboard UIs and customer portals with React, TypeScript, and Tailwind. Optimize for performance across devices. Work onsite with design and backend teams to deliver pixel-perfect interfaces.",
		company: "Tesla",
		location: "USA",
		salary: "100,000 - 120,000",
		createdAt: new Date("2022-03-15T23:31:24.396Z"),
		updatedAt: new Date("2022-03-15T23:31:24.396Z"),
	},
	{
		title: "Embedded Software Engineer",
		type: "Onsite",
		logo: "https://logos.hunter.io/tesla.com",
		company: "Tesla",
		location: "Austin, TX",
		salary: "110,000 - 140,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Develop Tesla vehicle firmware with Node.js tooling, TypeScript, and Rust. Work on Autopilot data pipelines and OTA updates.",
		isBookmarked: false,
		createdAt: new Date("2022-03-15T23:31:24.396Z"),
		updatedAt: new Date("2022-03-15T23:31:24.396Z"),
	},
	{
		title: "Full Stack Developer",
		type: "Onsite",
		logo: "https://logos.hunter.io/tesla.com",
		company: "Tesla",
		location: "Palo Alto, CA",
		salary: "115,000 - 140,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Build Tesla's energy management systems. Create dashboards for solar and Powerwall monitoring.",
		isBookmarked: false,
		createdAt: new Date("2022-04-12T13:20:00.000Z"),
		updatedAt: new Date("2022-04-12T13:20:00.000Z"),
	},
	{
		title: "Back End Developer",
		type: "Full Time",
		logo: "https://logos.hunter.io/tesla.com",
		company: "Tesla",
		location: "Fremont, CA",
		salary: "120,000 - 145,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Design APIs for Tesla's fleet management system. Handle millions of vehicle data points.",
		isBookmarked: false,
		createdAt: new Date("2022-05-24T09:50:00.000Z"),
		updatedAt: new Date("2022-05-24T09:50:00.000Z"),
	},
	{
		title: "DevOps Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/tesla.com",
		company: "Tesla",
		location: "Austin, TX",
		salary: "130,000 - 160,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Manage Tesla's manufacturing software infrastructure. Use Kubernetes, Terraform, and CI/CD.",
		isBookmarked: false,
		createdAt: new Date("2022-06-29T10:15:00.000Z"),
		updatedAt: new Date("2022-06-29T10:15:00.000Z"),
	},
	{
		title: "Data Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/tesla.com",
		company: "Tesla",
		location: "Remote",
		salary: "125,000 - 150,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Build data pipelines for Autopilot training data. Process terabytes of driving data daily.",
		isBookmarked: false,
		createdAt: new Date("2022-07-18T14:40:00.000Z"),
		updatedAt: new Date("2022-07-18T14:40:00.000Z"),
	},
	{
		title: "Mobile Developer",
		type: "Onsite",
		logo: "https://logos.hunter.io/tesla.com",
		company: "Tesla",
		location: "Palo Alto, CA",
		salary: "120,000 - 145,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Develop Tesla mobile app features for vehicle control and monitoring. Use React Native and native modules.",
		isBookmarked: false,
		createdAt: new Date("2022-08-09T08:30:00.000Z"),
		updatedAt: new Date("2022-08-09T08:30:00.000Z"),
	},
	{
		title: "Machine Learning Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/tesla.com",
		company: "Tesla",
		location: "Austin, TX",
		salary: "150,000 - 180,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Improve Autopilot perception models. Work with PyTorch, computer vision, and large datasets.",
		isBookmarked: false,
		createdAt: new Date("2022-09-01T11:55:00.000Z"),
		updatedAt: new Date("2022-09-01T11:55:00.000Z"),
	},
	{
		title: "QA Engineer",
		type: "Onsite",
		logo: "https://logos.hunter.io/tesla.com",
		company: "Tesla",
		location: "Fremont, CA",
		salary: "95,000 - 115,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Test vehicle infotainment systems. Automate testing for touchscreen interfaces and features.",
		isBookmarked: false,
		createdAt: new Date("2022-09-26T15:10:00.000Z"),
		updatedAt: new Date("2022-09-26T15:10:00.000Z"),
	},
	{
		title: "Security Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/tesla.com",
		company: "Tesla",
		location: "Remote",
		salary: "135,000 - 165,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Secure Tesla's connected vehicle systems. Perform penetration testing and vulnerability assessments.",
		isBookmarked: false,
		createdAt: new Date("2022-10-19T12:25:00.000Z"),
		updatedAt: new Date("2022-10-19T12:25:00.000Z"),
	},
	{
		title: "Front End Developer",
		type: "Onsite",
		logo: "https://logos.hunter.io/tesla.com",
		company: "Tesla",
		location: "Austin, TX",
		salary: "105,000 - 130,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Build internal tools for Gigafactory production lines. Use React, TypeScript, and real-time data.",
		isBookmarked: false,
		createdAt: new Date("2022-11-08T09:05:00.000Z"),
		updatedAt: new Date("2022-11-08T09:05:00.000Z"),
	},
	{
		title: "Product Manager",
		type: "Full Time",
		logo: "https://logos.hunter.io/tesla.com",
		company: "Tesla",
		location: "Palo Alto, CA",
		salary: "145,000 - 175,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Lead Tesla app features for vehicle purchasing and delivery. Improve customer digital experience.",
		isBookmarked: false,
		createdAt: new Date("2022-11-29T14:15:00.000Z"),
		updatedAt: new Date("2022-11-29T14:15:00.000Z"),
	},
	{
		title: "Systems Engineer",
		type: "Onsite",
		logo: "https://logos.hunter.io/tesla.com",
		company: "Tesla",
		location: "Fremont, CA",
		salary: "115,000 - 140,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Integrate software with vehicle hardware systems. Work on battery management and charging.",
		isBookmarked: false,
		createdAt: new Date("2022-12-16T10:45:00.000Z"),
		updatedAt: new Date("2022-12-16T10:45:00.000Z"),
	},
	{
		title: "Technical Program Manager",
		type: "Full Time",
		logo: "https://logos.hunter.io/tesla.com",
		company: "Tesla",
		location: "Austin, TX",
		salary: "140,000 - 170,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Coordinate Autopilot software releases. Manage timelines and cross-team dependencies.",
		isBookmarked: false,
		createdAt: new Date("2023-01-11T13:30:00.000Z"),
		updatedAt: new Date("2023-01-11T13:30:00.000Z"),
	},
	{
		title: "UI/UX Designer",
		type: "Onsite",
		logo: "https://logos.hunter.io/tesla.com",
		company: "Tesla",
		location: "Palo Alto, CA",
		salary: "115,000 - 140,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Design vehicle interface screens and mobile app experiences. Create prototypes and user flows.",
		isBookmarked: false,
		createdAt: new Date("2023-02-03T08:20:00.000Z"),
		updatedAt: new Date("2023-02-03T08:20:00.000Z"),
	},

	// Microsoft Jobs (15 positions)
	{
		title: "Software Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/microsoft.com",
		company: "Microsoft",
		location: "Redmond, WA",
		salary: "110,000 - 135,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Develop Azure cloud services with C#, .NET Core, and TypeScript. Build scalable microservices for enterprise customers.",
		isBookmarked: false,
		createdAt: new Date("2022-03-20T08:00:00.000Z"),
		updatedAt: new Date("2022-03-20T08:00:00.000Z"),
	},
	{
		title: "Front End Developer",
		type: "Hybrid",
		logo: "https://logos.hunter.io/microsoft.com",
		company: "Microsoft",
		location: "Remote",
		salary: "105,000 - 130,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Build Microsoft Teams web client with React, TypeScript, and Fluent UI. Focus on real-time collaboration.",
		isBookmarked: false,
		createdAt: new Date("2022-04-18T10:30:00.000Z"),
		updatedAt: new Date("2022-04-18T10:30:00.000Z"),
	},
	{
		title: "Back End Developer",
		type: "Full Time",
		logo: "https://logos.hunter.io/microsoft.com",
		company: "Microsoft",
		location: "Austin, TX",
		salary: "115,000 - 140,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Design APIs for Office 365 services. Use .NET, GraphQL, and Cosmos DB.",
		isBookmarked: false,
		createdAt: new Date("2022-05-25T14:45:00.000Z"),
		updatedAt: new Date("2022-05-25T14:45:00.000Z"),
	},
	{
		title: "DevOps Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/microsoft.com",
		company: "Microsoft",
		location: "Redmond, WA",
		salary: "130,000 - 160,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Manage Azure DevOps pipelines and infrastructure. Implement CI/CD for thousands of services.",
		isBookmarked: false,
		createdAt: new Date("2022-06-30T09:15:00.000Z"),
		updatedAt: new Date("2022-06-30T09:15:00.000Z"),
	},
	{
		title: "Full Stack Developer",
		type: "Remote",
		logo: "https://logos.hunter.io/microsoft.com",
		company: "Microsoft",
		location: "Remote",
		salary: "115,000 - 140,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Build LinkedIn learning features with React, Node.js, and Elasticsearch.",
		isBookmarked: false,
		createdAt: new Date("2022-07-22T11:50:00.000Z"),
		updatedAt: new Date("2022-07-22T11:50:00.000Z"),
	},
	{
		title: "Data Scientist",
		type: "Full Time",
		logo: "https://logos.hunter.io/microsoft.com",
		company: "Microsoft",
		location: "New York, NY",
		salary: "140,000 - 170,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Develop ML models for Bing search relevance. Use Python, Spark, and Azure ML.",
		isBookmarked: false,
		createdAt: new Date("2022-08-17T13:20:00.000Z"),
		updatedAt: new Date("2022-08-17T13:20:00.000Z"),
	},
	{
		title: "Security Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/microsoft.com",
		company: "Microsoft",
		location: "Redmond, WA",
		salary: "135,000 - 165,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Protect Microsoft 365 from security threats. Implement identity and access management solutions.",
		isBookmarked: false,
		createdAt: new Date("2022-09-14T08:40:00.000Z"),
		updatedAt: new Date("2022-09-14T08:40:00.000Z"),
	},
	{
		title: "Mobile Developer",
		type: "Hybrid",
		logo: "https://logos.hunter.io/microsoft.com",
		company: "Microsoft",
		location: "San Francisco, CA",
		salary: "120,000 - 145,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Develop Outlook mobile apps with React Native and C#. Focus on email and calendar features.",
		isBookmarked: false,
		createdAt: new Date("2022-10-11T10:55:00.000Z"),
		updatedAt: new Date("2022-10-11T10:55:00.000Z"),
	},
	{
		title: "Game Developer",
		type: "Full Time",
		logo: "https://logos.hunter.io/microsoft.com",
		company: "Microsoft",
		location: "Redmond, WA",
		salary: "115,000 - 140,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Build Xbox cloud gaming features with C++ and Azure. Optimize game streaming performance.",
		isBookmarked: false,
		createdAt: new Date("2022-11-04T15:30:00.000Z"),
		updatedAt: new Date("2022-11-04T15:30:00.000Z"),
	},
	{
		title: "Product Manager",
		type: "Full Time",
		logo: "https://logos.hunter.io/microsoft.com",
		company: "Microsoft",
		location: "Remote",
		salary: "145,000 - 175,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Lead Visual Studio Code strategy. Define features and work with open source community.",
		isBookmarked: false,
		createdAt: new Date("2022-11-28T12:05:00.000Z"),
		updatedAt: new Date("2022-11-28T12:05:00.000Z"),
	},
	{
		title: "QA Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/microsoft.com",
		company: "Microsoft",
		location: "Austin, TX",
		salary: "95,000 - 115,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Test Windows operating system features. Automate testing with C# and Selenium.",
		isBookmarked: false,
		createdAt: new Date("2022-12-19T09:35:00.000Z"),
		updatedAt: new Date("2022-12-19T09:35:00.000Z"),
	},
	{
		title: "Technical Writer",
		type: "Full Time",
		logo: "https://logos.hunter.io/microsoft.com",
		company: "Microsoft",
		location: "Redmond, WA",
		salary: "90,000 - 110,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Document Azure SDKs and APIs. Create tutorials and code samples for developers.",
		isBookmarked: false,
		createdAt: new Date("2023-01-06T14:25:00.000Z"),
		updatedAt: new Date("2023-01-06T14:25:00.000Z"),
	},
	{
		title: "UX Designer",
		type: "Full Time",
		logo: "https://logos.hunter.io/microsoft.com",
		company: "Microsoft",
		location: "Remote",
		salary: "115,000 - 140,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Design Windows 11 user experiences. Create accessible and intuitive interfaces.",
		isBookmarked: false,
		createdAt: new Date("2023-01-23T11:10:00.000Z"),
		updatedAt: new Date("2023-01-23T11:10:00.000Z"),
	},
	{
		title: "Software Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/microsoft.com",
		company: "Microsoft",
		location: "Vancouver, BC",
		salary: "100,000 - 120,000",
		currency: "CAD",
		experienceLevel: "Entry Level",
		description:
			"Join Microsoft's new grad program. Work on Azure services with mentorship from senior engineers.",
		isBookmarked: false,
		createdAt: new Date("2023-02-10T08:50:00.000Z"),
		updatedAt: new Date("2023-02-10T08:50:00.000Z"),
	},
	{
		title: "AI Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/microsoft.com",
		company: "Microsoft",
		location: "Redmond, WA",
		salary: "140,000 - 170,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Develop AI features for Microsoft Copilot. Integrate LLMs into Office products.",
		isBookmarked: false,
		createdAt: new Date("2023-02-28T13:15:00.000Z"),
		updatedAt: new Date("2023-02-28T13:15:00.000Z"),
	},

	// Apple Jobs (15 positions)
	{
		title: "iOS Developer",
		type: "Onsite",
		logo: "https://logos.hunter.io/apple.com",
		company: "Apple",
		location: "Cupertino, CA",
		salary: "130,000 - 160,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Develop iOS system apps with Swift and UIKit. Focus on performance and user privacy.",
		isBookmarked: false,
		createdAt: new Date("2022-03-25T09:00:00.000Z"),
		updatedAt: new Date("2022-03-25T09:00:00.000Z"),
	},
	{
		title: "Full Stack Developer",
		type: "Hybrid",
		logo: "https://logos.hunter.io/apple.com",
		company: "Apple",
		location: "Austin, TX",
		salary: "120,000 - 145,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Build Apple Music web player with React, Node.js, and media streaming technologies.",
		isBookmarked: false,
		createdAt: new Date("2022-04-22T11:20:00.000Z"),
		updatedAt: new Date("2022-04-22T11:20:00.000Z"),
	},
	{
		title: "Back End Developer",
		type: "Full Time",
		logo: "https://logos.hunter.io/apple.com",
		company: "Apple",
		location: "Cupertino, CA",
		salary: "125,000 - 150,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Design iCloud backend services. Use Swift, Vapor, and distributed systems.",
		isBookmarked: false,
		createdAt: new Date("2022-05-27T14:35:00.000Z"),
		updatedAt: new Date("2022-05-27T14:35:00.000Z"),
	},
	{
		title: "Machine Learning Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/apple.com",
		company: "Apple",
		location: "Seattle, WA",
		salary: "150,000 - 180,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Improve Siri's natural language understanding. Use Core ML, Python, and deep learning.",
		isBookmarked: false,
		createdAt: new Date("2022-06-23T10:05:00.000Z"),
		updatedAt: new Date("2022-06-23T10:05:00.000Z"),
	},
	{
		title: "DevOps Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/apple.com",
		company: "Apple",
		location: "Remote",
		salary: "130,000 - 160,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Manage Apple's cloud infrastructure. Use Kubernetes, Terraform, and CI/CD pipelines.",
		isBookmarked: false,
		createdAt: new Date("2022-07-28T13:50:00.000Z"),
		updatedAt: new Date("2022-07-28T13:50:00.000Z"),
	},
	{
		title: "Front End Developer",
		type: "Onsite",
		logo: "https://logos.hunter.io/apple.com",
		company: "Apple",
		location: "Cupertino, CA",
		salary: "115,000 - 140,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Build Apple.com and product pages with modern JavaScript and WebGL.",
		isBookmarked: false,
		createdAt: new Date("2022-08-24T09:30:00.000Z"),
		updatedAt: new Date("2022-08-24T09:30:00.000Z"),
	},
	{
		title: "Hardware Engineer",
		type: "Onsite",
		logo: "https://logos.hunter.io/apple.com",
		company: "Apple",
		location: "Cupertino, CA",
		salary: "135,000 - 165,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Design M-series chips and hardware architecture. Work on next-generation processors.",
		isBookmarked: false,
		createdAt: new Date("2022-09-21T11:15:00.000Z"),
		updatedAt: new Date("2022-09-21T11:15:00.000Z"),
	},
	{
		title: "Security Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/apple.com",
		company: "Apple",
		location: "Austin, TX",
		salary: "140,000 - 170,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Secure iOS and macOS platforms. Implement encryption and security features.",
		isBookmarked: false,
		createdAt: new Date("2022-10-18T15:40:00.000Z"),
		updatedAt: new Date("2022-10-18T15:40:00.000Z"),
	},
	{
		title: "UI/UX Designer",
		type: "Onsite",
		logo: "https://logos.hunter.io/apple.com",
		company: "Apple",
		location: "Cupertino, CA",
		salary: "120,000 - 145,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Design visionOS interfaces for Apple Vision Pro. Create spatial computing experiences.",
		isBookmarked: false,
		createdAt: new Date("2022-11-15T10:55:00.000Z"),
		updatedAt: new Date("2022-11-15T10:55:00.000Z"),
	},
	{
		title: "QA Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/apple.com",
		company: "Apple",
		location: "Remote",
		salary: "100,000 - 120,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Test iOS releases for bugs and performance. Automate testing with XCTest.",
		isBookmarked: false,
		createdAt: new Date("2022-12-08T13:20:00.000Z"),
		updatedAt: new Date("2022-12-08T13:20:00.000Z"),
	},
	{
		title: "Data Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/apple.com",
		company: "Apple",
		location: "Seattle, WA",
		salary: "130,000 - 160,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Build data pipelines for Apple Maps. Process geospatial data and user analytics.",
		isBookmarked: false,
		createdAt: new Date("2023-01-05T09:45:00.000Z"),
		updatedAt: new Date("2023-01-05T09:45:00.000Z"),
	},
	{
		title: "Product Manager",
		type: "Full Time",
		logo: "https://logos.hunter.io/apple.com",
		company: "Apple",
		location: "Cupertino, CA",
		salary: "150,000 - 180,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Lead Apple Fitness+ features. Define product roadmap and user experiences.",
		isBookmarked: false,
		createdAt: new Date("2023-01-26T14:30:00.000Z"),
		updatedAt: new Date("2023-01-26T14:30:00.000Z"),
	},
	{
		title: "Technical Writer",
		type: "Full Time",
		logo: "https://logos.hunter.io/apple.com",
		company: "Apple",
		location: "Austin, TX",
		salary: "95,000 - 115,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Write developer documentation for Swift and Xcode. Create tutorials and guides.",
		isBookmarked: false,
		createdAt: new Date("2023-02-14T08:10:00.000Z"),
		updatedAt: new Date("2023-02-14T08:10:00.000Z"),
	},
	{
		title: "Software Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/apple.com",
		company: "Apple",
		location: "San Diego, CA",
		salary: "110,000 - 135,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Develop Apple Pay features with Swift and Objective-C. Focus on security and reliability.",
		isBookmarked: false,
		createdAt: new Date("2023-03-03T11:55:00.000Z"),
		updatedAt: new Date("2023-03-03T11:55:00.000Z"),
	},
	{
		title: "AR/VR Engineer",
		type: "Onsite",
		logo: "https://logos.hunter.io/apple.com",
		company: "Apple",
		location: "Cupertino, CA",
		salary: "140,000 - 170,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Build augmented reality features for Vision Pro. Use RealityKit and SwiftUI.",
		isBookmarked: false,
		createdAt: new Date("2023-03-20T15:20:00.000Z"),
		updatedAt: new Date("2023-03-20T15:20:00.000Z"),
	},

	// Netflix Jobs (10 positions)
	{
		title: "Front End Developer",
		type: "Full Time",
		logo: "https://logos.hunter.io/netflix.com",
		company: "Netflix",
		location: "Los Gatos, CA",
		salary: "130,000 - 160,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Build Netflix streaming interface with React, TypeScript, and WebGL. Optimize for all devices.",
		isBookmarked: false,
		createdAt: new Date("2022-04-03T10:00:00.000Z"),
		updatedAt: new Date("2022-04-03T10:00:00.000Z"),
	},
	{
		title: "Back End Developer",
		type: "Full Time",
		logo: "https://logos.hunter.io/netflix.com",
		company: "Netflix",
		location: "Remote",
		salary: "135,000 - 165,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Design recommendation engine APIs. Use Java, Spring Boot, and Cassandra.",
		isBookmarked: false,
		createdAt: new Date("2022-05-12T14:20:00.000Z"),
		updatedAt: new Date("2022-05-12T14:20:00.000Z"),
	},
	{
		title: "DevOps Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/netflix.com",
		company: "Netflix",
		location: "Los Gatos, CA",
		salary: "140,000 - 170,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Manage Netflix's AWS infrastructure. Implement chaos engineering and auto-scaling.",
		isBookmarked: false,
		createdAt: new Date("2022-06-20T09:30:00.000Z"),
		updatedAt: new Date("2022-06-20T09:30:00.000Z"),
	},
	{
		title: "Data Scientist",
		type: "Full Time",
		logo: "https://logos.hunter.io/netflix.com",
		company: "Netflix",
		location: "Remote",
		salary: "150,000 - 180,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Improve Netflix's personalization algorithms. Use Python, Spark, and ML.",
		isBookmarked: false,
		createdAt: new Date("2022-07-25T11:45:00.000Z"),
		updatedAt: new Date("2022-07-25T11:45:00.000Z"),
	},
	{
		title: "Full Stack Developer",
		type: "Hybrid",
		logo: "https://logos.hunter.io/netflix.com",
		company: "Netflix",
		location: "Los Angeles, CA",
		salary: "125,000 - 150,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Build internal tools for content production. Use React, Node.js, and video processing.",
		isBookmarked: false,
		createdAt: new Date("2022-08-29T08:15:00.000Z"),
		updatedAt: new Date("2022-08-29T08:15:00.000Z"),
	},
	{
		title: "QA Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/netflix.com",
		company: "Netflix",
		location: "Remote",
		salary: "110,000 - 135,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Test streaming quality across devices. Automate playback testing and performance monitoring.",
		isBookmarked: false,
		createdAt: new Date("2022-10-04T13:55:00.000Z"),
		updatedAt: new Date("2022-10-04T13:55:00.000Z"),
	},
	{
		title: "Mobile Developer",
		type: "Full Time",
		logo: "https://logos.hunter.io/netflix.com",
		company: "Netflix",
		location: "Los Gatos, CA",
		salary: "130,000 - 160,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Enhance Netflix mobile apps with native features. Use Swift for iOS and Kotlin for Android.",
		isBookmarked: false,
		createdAt: new Date("2022-11-09T10:40:00.000Z"),
		updatedAt: new Date("2022-11-09T10:40:00.000Z"),
	},
	{
		title: "Security Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/netflix.com",
		company: "Netflix",
		location: "Remote",
		salary: "140,000 - 170,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Protect Netflix from piracy and security threats. Implement DRM and access controls.",
		isBookmarked: false,
		createdAt: new Date("2022-12-12T12:25:00.000Z"),
		updatedAt: new Date("2022-12-12T12:25:00.000Z"),
	},
	{
		title: "Product Designer",
		type: "Full Time",
		logo: "https://logos.hunter.io/netflix.com",
		company: "Netflix",
		location: "Los Gatos, CA",
		salary: "125,000 - 150,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Design Netflix user experiences for TV and mobile. Create intuitive interfaces for content discovery.",
		isBookmarked: false,
		createdAt: new Date("2023-01-17T09:05:00.000Z"),
		updatedAt: new Date("2023-01-17T09:05:00.000Z"),
	},
	{
		title: "Technical Program Manager",
		type: "Full Time",
		logo: "https://logos.hunter.io/netflix.com",
		company: "Netflix",
		location: "Remote",
		salary: "145,000 - 175,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Lead streaming infrastructure initiatives. Coordinate engineering teams and feature releases.",
		isBookmarked: false,
		createdAt: new Date("2023-02-21T14:50:00.000Z"),
		updatedAt: new Date("2023-02-21T14:50:00.000Z"),
	},

	// Adobe Jobs (10 positions)
	{
		title: "Software Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/adobe.com",
		company: "Adobe",
		location: "San Jose, CA",
		salary: "115,000 - 140,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Build Creative Cloud desktop apps with C++ and JavaScript. Focus on performance and features.",
		isBookmarked: false,
		createdAt: new Date("2022-04-07T08:30:00.000Z"),
		updatedAt: new Date("2022-04-07T08:30:00.000Z"),
	},
	{
		title: "Front End Developer",
		type: "Remote",
		logo: "https://logos.hunter.io/adobe.com",
		company: "Adobe",
		location: "Remote",
		salary: "110,000 - 135,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Develop Adobe Express web editor with React, TypeScript, and Canvas APIs.",
		isBookmarked: false,
		createdAt: new Date("2022-05-16T10:15:00.000Z"),
		updatedAt: new Date("2022-05-16T10:15:00.000Z"),
	},
	{
		title: "Back End Developer",
		type: "Full Time",
		logo: "https://logos.hunter.io/adobe.com",
		company: "Adobe",
		location: "Lehi, UT",
		salary: "115,000 - 140,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Design APIs for Adobe Document Cloud. Use Java, Spring, and microservices.",
		isBookmarked: false,
		createdAt: new Date("2022-06-27T13:40:00.000Z"),
		updatedAt: new Date("2022-06-27T13:40:00.000Z"),
	},
	{
		title: "Machine Learning Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/adobe.com",
		company: "Adobe",
		location: "San Jose, CA",
		salary: "145,000 - 175,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Add AI features to Photoshop. Use TensorFlow, PyTorch, and computer vision.",
		isBookmarked: false,
		createdAt: new Date("2022-07-29T09:55:00.000Z"),
		updatedAt: new Date("2022-07-29T09:55:00.000Z"),
	},
	{
		title: "DevOps Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/adobe.com",
		company: "Adobe",
		location: "Remote",
		salary: "125,000 - 150,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Manage Adobe's cloud infrastructure. Use AWS, Kubernetes, and CI/CD pipelines.",
		isBookmarked: false,
		createdAt: new Date("2022-08-31T14:20:00.000Z"),
		updatedAt: new Date("2022-08-31T14:20:00.000Z"),
	},
	{
		title: "Full Stack Developer",
		type: "Hybrid",
		logo: "https://logos.hunter.io/adobe.com",
		company: "Adobe",
		location: "San Francisco, CA",
		salary: "120,000 - 145,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Build Adobe Analytics dashboards with React, Node.js, and data visualization.",
		isBookmarked: false,
		createdAt: new Date("2022-10-06T11:10:00.000Z"),
		updatedAt: new Date("2022-10-06T11:10:00.000Z"),
	},
	{
		title: "Mobile Developer",
		type: "Full Time",
		logo: "https://logos.hunter.io/adobe.com",
		company: "Adobe",
		location: "Austin, TX",
		salary: "115,000 - 140,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Develop Adobe Lightroom mobile with Swift and Kotlin. Focus on photo editing features.",
		isBookmarked: false,
		createdAt: new Date("2022-11-14T08:45:00.000Z"),
		updatedAt: new Date("2022-11-14T08:45:00.000Z"),
	},
	{
		title: "UI/UX Designer",
		type: "Full Time",
		logo: "https://logos.hunter.io/adobe.com",
		company: "Adobe",
		location: "Remote",
		salary: "115,000 - 140,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Design Adobe XD and Creative Cloud interfaces. Create intuitive design tools.",
		isBookmarked: false,
		createdAt: new Date("2022-12-20T12:30:00.000Z"),
		updatedAt: new Date("2022-12-20T12:30:00.000Z"),
	},
	{
		title: "QA Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/adobe.com",
		company: "Adobe",
		location: "Lehi, UT",
		salary: "95,000 - 115,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Test Adobe Acrobat features. Automate testing with Selenium and Python.",
		isBookmarked: false,
		createdAt: new Date("2023-01-24T09:35:00.000Z"),
		updatedAt: new Date("2023-01-24T09:35:00.000Z"),
	},
	{
		title: "Product Manager",
		type: "Full Time",
		logo: "https://logos.hunter.io/adobe.com",
		company: "Adobe",
		location: "San Jose, CA",
		salary: "140,000 - 170,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Lead Adobe Premiere Pro features. Define roadmap for video editing tools.",
		isBookmarked: false,
		createdAt: new Date("2023-02-27T15:15:00.000Z"),
		updatedAt: new Date("2023-02-27T15:15:00.000Z"),
	},

	// Additional companies for variety (15 positions across different companies)
	{
		title: "Full Stack Developer",
		type: "Remote",
		logo: "https://logos.hunter.io/shopify.com",
		company: "Shopify",
		location: "Remote",
		salary: "110,000 - 135,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Build e-commerce features with React, Node.js, and GraphQL. Focus on merchant tools.",
		isBookmarked: false,
		createdAt: new Date("2022-04-14T10:30:00.000Z"),
		updatedAt: new Date("2022-04-14T10:30:00.000Z"),
	},
	{
		title: "Software Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/salesforce.com",
		company: "Salesforce",
		location: "San Francisco, CA",
		salary: "115,000 - 140,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Develop CRM platforms with Apex, Java, and React. Build enterprise features.",
		isBookmarked: false,
		createdAt: new Date("2022-05-19T13:15:00.000Z"),
		updatedAt: new Date("2022-05-19T13:15:00.000Z"),
	},
	{
		title: "Front End Developer",
		type: "Hybrid",
		logo: "https://logos.hunter.io/airbnb.com",
		company: "Airbnb",
		location: "San Francisco, CA",
		salary: "120,000 - 145,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Build Airbnb search and booking flows with React, TypeScript, and Maps APIs.",
		isBookmarked: false,
		createdAt: new Date("2022-06-16T08:50:00.000Z"),
		updatedAt: new Date("2022-06-16T08:50:00.000Z"),
	},
	{
		title: "Back End Developer",
		type: "Remote",
		logo: "https://logos.hunter.io/uber.com",
		company: "Uber",
		location: "Remote",
		salary: "125,000 - 150,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Design Uber's dispatch algorithms. Use Go, Kafka, and distributed systems.",
		isBookmarked: false,
		createdAt: new Date("2022-07-21T11:40:00.000Z"),
		updatedAt: new Date("2022-07-21T11:40:00.000Z"),
	},
	{
		title: "Data Scientist",
		type: "Full Time",
		logo: "https://logos.hunter.io/linkedin.com",
		company: "LinkedIn",
		location: "Sunnyvale, CA",
		salary: "135,000 - 165,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Improve job recommendations with ML. Use Python, Spark, and Hadoop.",
		isBookmarked: false,
		createdAt: new Date("2022-08-25T14:55:00.000Z"),
		updatedAt: new Date("2022-08-25T14:55:00.000Z"),
	},
	{
		title: "Mobile Developer",
		type: "Full Time",
		logo: "https://logos.hunter.io/pinterest.com",
		company: "Pinterest",
		location: "San Francisco, CA",
		salary: "115,000 - 140,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Build Pinterest mobile apps with Swift and Kotlin. Focus on visual discovery.",
		isBookmarked: false,
		createdAt: new Date("2022-09-22T09:25:00.000Z"),
		updatedAt: new Date("2022-09-22T09:25:00.000Z"),
	},
	{
		title: "DevOps Engineer",
		type: "Remote",
		logo: "https://logos.hunter.io/slack.com",
		company: "Slack",
		location: "Remote",
		salary: "130,000 - 160,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Manage Slack's infrastructure. Use Kubernetes, Terraform, and monitoring tools.",
		isBookmarked: false,
		createdAt: new Date("2022-10-27T12:10:00.000Z"),
		updatedAt: new Date("2022-10-27T12:10:00.000Z"),
	},
	{
		title: "Full Stack Developer",
		type: "Hybrid",
		logo: "https://logos.hunter.io/dropbox.com",
		company: "Dropbox",
		location: "Remote",
		salary: "115,000 - 140,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Build file sharing features with React, Python, and Go. Focus on sync performance.",
		isBookmarked: false,
		createdAt: new Date("2022-11-23T15:35:00.000Z"),
		updatedAt: new Date("2022-11-23T15:35:00.000Z"),
	},
	{
		title: "Security Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/twitter.com",
		company: "Twitter (X)",
		location: "San Francisco, CA",
		salary: "135,000 - 165,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Secure Twitter's platform from abuse. Implement authentication and bot detection.",
		isBookmarked: false,
		createdAt: new Date("2022-12-14T08:05:00.000Z"),
		updatedAt: new Date("2022-12-14T08:05:00.000Z"),
	},
	{
		title: "QA Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/square.com",
		company: "Square",
		location: "Remote",
		salary: "100,000 - 120,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Test payment processing systems. Automate testing for financial transactions.",
		isBookmarked: false,
		createdAt: new Date("2023-01-18T10:50:00.000Z"),
		updatedAt: new Date("2023-01-18T10:50:00.000Z"),
	},
	{
		title: "Software Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/intel.com",
		company: "Intel",
		location: "Hillsboro, OR",
		salary: "105,000 - 130,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Develop driver software for Intel chips. Use C, C++, and assembly.",
		isBookmarked: false,
		createdAt: new Date("2023-02-09T13:45:00.000Z"),
		updatedAt: new Date("2023-02-09T13:45:00.000Z"),
	},
	{
		title: "Front End Developer",
		type: "Remote",
		logo: "https://logos.hunter.io/spotify.com",
		company: "Spotify",
		location: "Remote",
		salary: "115,000 - 140,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Build Spotify's web player with React, TypeScript, and Web Audio API.",
		isBookmarked: false,
		createdAt: new Date("2023-03-02T09:20:00.000Z"),
		updatedAt: new Date("2023-03-02T09:20:00.000Z"),
	},
	{
		title: "Back End Developer",
		type: "Hybrid",
		logo: "https://logos.hunter.io/paypal.com",
		company: "PayPal",
		location: "San Jose, CA",
		salary: "120,000 - 145,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Design payment processing APIs. Use Java, Kafka, and distributed databases.",
		isBookmarked: false,
		createdAt: new Date("2023-03-23T14:30:00.000Z"),
		updatedAt: new Date("2023-03-23T14:30:00.000Z"),
	},
	{
		title: "Machine Learning Engineer",
		type: "Full Time",
		logo: "https://logos.hunter.io/nvidia.com",
		company: "NVIDIA",
		location: "Santa Clara, CA",
		salary: "150,000 - 180,000",
		currency: "USD",
		experienceLevel: "Senior",
		description:
			"Optimize ML models for GPU acceleration. Use CUDA, Python, and deep learning.",
		isBookmarked: false,
		createdAt: new Date("2023-04-06T11:55:00.000Z"),
		updatedAt: new Date("2023-04-06T11:55:00.000Z"),
	},
	{
		title: "Full Stack Developer",
		type: "Remote",
		logo: "https://logos.hunter.io/zoom.com",
		company: "Zoom",
		location: "Remote",
		salary: "115,000 - 140,000",
		currency: "USD",
		experienceLevel: "Intermediate",
		description:
			"Build Zoom web client features with React, Node.js, and WebRTC.",
		isBookmarked: false,
		createdAt: new Date("2023-04-18T10:15:00.000Z"),
		updatedAt: new Date("2023-04-18T10:15:00.000Z"),
	},
];

const users = [
	{
		firstName: "John",
		lastName: "Doe",
		email: "johndoe@gmail.com",
		password: bcrypt.hashSync("123456", 10),
		createdAt: new Date("2022-03-15T23:31:24.396Z"),
		updatedAt: new Date("2022-03-15T23:31:24.396Z"),
	},
	{
		firstName: "Jane",
		lastName: "Doe",
		email: "janedoe@gmail.com",
		password: bcrypt.hashSync("123456", 10),
		createdAt: new Date("2022-03-15T23:31:24.396Z"),
		updatedAt: new Date("2022-03-15T23:31:24.396Z"),
	},
	{
		firstName: "Bob",
		lastName: "Smith",
		email: "bobsmith@gmail.com",
		password: bcrypt.hashSync("123456", 10),
		createdAt: new Date("2022-03-15T23:31:24.396Z"),
		updatedAt: new Date("2022-03-15T23:31:24.396Z"),
	},
	{
		firstName: "Kevin",
		lastName: "Smith",
		email: "kevinsmith@gmail.com",
		password: bcrypt.hashSync("123456", 10),
		createdAt: new Date("2022-03-15T23:31:24.396Z"),
		updatedAt: new Date("2022-03-15T23:31:24.396Z"),
	},
	{
		firstName: "Sarah",
		lastName: "Smith",
		email: "sarahsmith@gmail.com",
		password: bcrypt.hashSync("123456", 10),
		createdAt: new Date("2022-03-15T23:31:24.396Z"),
		updatedAt: new Date("2022-03-15T23:31:24.396Z"),
	},
	{
		firstName: "Henry",
		lastName: "Smith",
		email: "henrysmith@gmail.com",
		password: bcrypt.hashSync("123456", 10),
		createdAt: new Date("2022-03-15T23:31:24.396Z"),
		updatedAt: new Date("2022-03-15T23:31:24.396Z"),
	},
];

const seed = async () => {
	try {
		await Job.insertMany(jobs);
		await User.insertMany(users);
		logger.info("Seeding successful");
	} catch (error) {
		logger.error("Seeding failed", error);
	}
};

connectDb(seed);
